import "./globals.css";
import { ThemeProvider } from "@/ThemeContext";
import ThemeState from "./main";
import PreventZoom from "./preventZoom";
import { Viewport } from 'next'



export const metadata = {
  title: "Marcus Ekström",
  description: "Generated by create next app",
  /* viewport: "width=device-width, initial-scale=0.5, user-scalable=0", */
};

 
export const viewport = {
  width: 'device-width',
  initialScale: 0.5,
  userScalable: false,
  // Also supported by less commonly used
  // interactiveWidget: 'resizes-visual',
}

/* export const App() {

}
 */



export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <ThemeProvider>
        {/* <PreventZoom></PreventZoom> */}
        <ThemeState></ThemeState> {/* see main.jsx, adds or removes the 'dark' mode with tailwind */}
        <body className="font-sourceSans">{children}</body>
      </ThemeProvider>
    </html>
  );
}
