import "./globals.css";
import { ThemeProvider } from "@/ThemeContext";
import ThemeState from "./main";
import PreventZoom from "./preventZoom";
import { SectionRefProvider } from "@/SectionRefContext";
import { Analytics } from "@vercel/analytics/react"



export const metadata = {
  title: "Marcus Ekström",
  description: "Generated by create next app",
  /* viewport: "width=device-width, initial-scale=0.5, user-scalable=0", */
};

 
export const viewport = {
  /* width: 'device-width',
  initialScale: 1.0,
  userScalable: false, */
  // Also supported by less commonly used
  // interactiveWidget: 'resizes-visual',
}

/* export const App() {

}
 */



export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <ThemeProvider>
        <SectionRefProvider>
          <PreventZoom></PreventZoom> {/* prevent zoom on mobile */}
          <ThemeState></ThemeState> {/* see main.jsx, runs an useEffect to add "darkmode" with tailwind */}
          <body className="font-sourceSans bg-[#FFFFFF] dark:bg-[#23272F]"> {/* affects the color you see at the top of the page on mobile */}
            {children}
            <Analytics/>
          </body>
        </SectionRefProvider>
      </ThemeProvider>
    </html>
  );
}
