import "./globals.css";
import { ThemeProvider } from "@/ThemeContext";
import ThemeState from "./main";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* export const App() {

}
 */



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>
        <ThemeState></ThemeState>
        <body className="font-sourceSans">{children}</body>
      </ThemeProvider>
    </html>
  );
}
